spring:
  datasource:
    url: jdbc:mariadb:tcp://localhost/~/sensor;MVCC=TRUE
    username: root
    password: 1234
    driver-class-name: org.mariadb.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace