spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sensor
    driver-class-name: org.mariadb.jdbc.Driver
    username: min
    password: 12345
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
mybatis:
  type-aliases-package: kr.co.fastcampus.eatgo
  mapper-locations: mybatis/mapper/**/*.xml